# Generated by Django 3.2.3 on 2021-10-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resset_password_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
