# Generated by Django 3.2.3 on 2021-10-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_resset_password_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='resset_password_code',
            new_name='reset_password_code',
        ),
    ]
