# Generated by Django 3.2.3 on 2021-10-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_resset_password_code_user_reset_password_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reset_password_code',
            new_name='otp',
        ),
    ]
