# Generated by Django 3.2.3 on 2021-10-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_reset_password_code_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
