# Generated by Django 3.2.3 on 2021-10-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_otp_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='change_password_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
