# Generated by Django 3.2 on 2021-04-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='stories',
            field=models.ManyToManyField(related_name='highlights', to='story.Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('d', 'deactive')], default='a', max_length=1),
        ),
    ]
